apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jnayak1482/kind_github_argocd  # ✅ Correct GitHub repo URL
    targetRevision: main
    path: manifest  # ✅ Correct directory
    directory:
      recurse: false  # ✅ Prevents ArgoCD from reading non-YAML files
      include: "*.yaml"  # ✅ Only apply Kubernetes YAML files
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
